name: Run autotests

on:
  workflow_dispatch:
    inputs:
      depoyment_target:
        description: select tests to run
        required: true
        type: choice
        default: all
        options:
          - all
jobs:
  run-tests:
    runs-on: Windows 10
    name: Tests
    steps:
      - name: Copy source code
        uses: action/checkout@v4
      - name: Set up Python env
        uses: actions/setup-python@v5
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v
